import type { Recipe } from './types';

const RECIPES: Recipe[] = [
  {
    id: '1',
    slug: 'creamy-tomato-pasta',
    title: 'Creamy Tomato Pasta',
    description: 'A rich and creamy tomato pasta dish that comes together in under 30 minutes. Perfect for a weeknight dinner.',
    cuisine: 'Italian',
    mealType: 'Dinner',
    dietaryRestrictions: ['Vegetarian'],
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    ingredients: [
      { name: 'Pasta', quantity: '400g' },
      { name: 'Canned crushed tomatoes', quantity: '800g' },
      { name: 'Heavy cream', quantity: '1/2 cup' },
      { name: 'Garlic', quantity: '3 cloves, minced' },
      { name: 'Onion', quantity: '1, chopped' },
      { name: 'Olive oil', quantity: '2 tbsp' },
      { name: 'Parmesan cheese', quantity: '1/2 cup, grated' },
      { name: 'Fresh basil', quantity: 'for garnish' },
      { name: 'Salt and pepper', quantity: 'to taste' },
    ],
    instructions: [
      'Cook pasta according to package directions. Drain, reserving 1 cup of pasta water.',
      'While pasta is cooking, heat olive oil in a large skillet over medium heat. Add onion and cook until softened, about 5 minutes.',
      'Add garlic and cook for another minute until fragrant.',
      'Pour in crushed tomatoes, season with salt and pepper, and bring to a simmer. Cook for 10 minutes.',
      'Reduce heat to low and stir in heavy cream and Parmesan cheese. Cook until cheese is melted and sauce is smooth.',
      'Add cooked pasta to the skillet and toss to coat. If the sauce is too thick, add a splash of reserved pasta water.',
      'Serve immediately, garnished with fresh basil.',
    ],
    imageId: 'creamy-tomato-pasta',
    nutritionalInfo: { calories: '550 kcal', protein: '15g', carbs: '70g', fat: '22g' },
  },
  {
    id: '2',
    slug: 'vegan-chocolate-avocado-mousse',
    title: 'Vegan Chocolate Avocado Mousse',
    description: 'A surprisingly decadent and healthy dessert. This vegan mousse is rich, creamy, and made with simple ingredients.',
    cuisine: 'International',
    mealType: 'Dessert',
    dietaryRestrictions: ['Vegan', 'Gluten-Free'],
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    ingredients: [
      { name: 'Ripe avocados', quantity: '2' },
      { name: 'Unsweetened cocoa powder', quantity: '1/2 cup' },
      { name: 'Maple syrup', quantity: '1/4 cup' },
      { name: 'Plant-based milk (e.g., almond)', quantity: '1/4 cup' },
      { name: 'Vanilla extract', quantity: '1 tsp' },
      { name: 'Pinch of salt', quantity: '1' },
    ],
    instructions: [
      'Combine all ingredients in a high-speed blender or food processor.',
      'Blend until completely smooth and creamy, scraping down the sides as needed.',
      'Taste and adjust sweetness if desired.',
      'Divide the mousse into two serving glasses.',
      'Chill in the refrigerator for at least 30 minutes before serving.',
      'Garnish with berries or chocolate shavings if desired.',
    ],
    imageId: 'vegan-chocolate-avocado-mousse',
    nutritionalInfo: { calories: '350 kcal', protein: '6g', carbs: '40g', fat: '20g' },
  },
  {
    id: '3',
    slug: 'gluten-free-banana-bread',
    title: 'Gluten-Free Banana Bread',
    description: 'Moist, flavorful, and easy to make, this banana bread is a gluten-free treat that everyone will love.',
    cuisine: 'American',
    mealType: 'Snack',
    dietaryRestrictions: ['Gluten-Free', 'Vegetarian'],
    prepTime: 15,
    cookTime: 55,
    servings: 10,
    ingredients: [
      { name: 'Ripe bananas', quantity: '3, mashed' },
      { name: 'Gluten-free all-purpose flour', quantity: '1 3/4 cups' },
      { name: 'Brown sugar', quantity: '3/4 cup' },
      { name: 'Melted coconut oil or butter', quantity: '1/2 cup' },
      { name: 'Eggs', quantity: '2' },
      { name: 'Baking soda', quantity: '1 tsp' },
      { name: 'Vanilla extract', quantity: '1 tsp' },
      { name: 'Cinnamon', quantity: '1/2 tsp' },
      { name: 'Salt', quantity: '1/4 tsp' },
    ],
    instructions: [
      'Preheat oven to 350°F (175°C). Grease a 9x5 inch loaf pan.',
      'In a large bowl, mix together the mashed bananas, brown sugar, melted oil, and eggs.',
      'In a separate bowl, whisk together the gluten-free flour, baking soda, vanilla, cinnamon, and salt.',
      'Add the dry ingredients to the wet ingredients and stir until just combined. Do not overmix.',
      'Pour the batter into the prepared loaf pan.',
      'Bake for 50-60 minutes, or until a toothpick inserted into the center comes out clean.',
      'Let cool in the pan for 10 minutes before transferring to a wire rack to cool completely.',
    ],
    imageId: 'gluten-free-banana-bread',
    nutritionalInfo: { calories: '250 kcal', protein: '4g', carbs: '35g', fat: '11g' },
  },
  {
    id: '4',
    slug: 'spicy-chicken-stir-fry',
    title: 'Spicy Chicken Stir-Fry',
    description: 'A quick, healthy, and customizable stir-fry with a kick. Perfect for using up leftover veggies.',
    cuisine: 'Asian',
    mealType: 'Dinner',
    dietaryRestrictions: [],
    prepTime: 20,
    cookTime: 15,
    servings: 3,
    ingredients: [
        { name: 'Chicken breast', quantity: '1 lb, thinly sliced' },
        { name: 'Broccoli florets', quantity: '2 cups' },
        { name: 'Bell pepper', quantity: '1, sliced' },
        { name: 'Soy sauce', quantity: '1/4 cup' },
        { name: 'Sriracha or chili garlic sauce', quantity: '1 tbsp' },
        { name: 'Honey or maple syrup', quantity: '1 tbsp' },
        { name: 'Sesame oil', quantity: '1 tbsp' },
        { name: 'Ginger', quantity: '1 inch, grated' },
        { name: 'Garlic', quantity: '2 cloves, minced' },
        { name: 'Cooked rice', quantity: 'for serving' },
    ],
    instructions: [
        'In a small bowl, whisk together soy sauce, sriracha, and honey. Set aside.',
        'Heat sesame oil in a large wok or skillet over high heat.',
        'Add chicken and cook until browned and cooked through. Remove from skillet.',
        'Add broccoli, bell pepper, ginger, and garlic to the skillet. Stir-fry for 3-4 minutes until vegetables are crisp-tender.',
        'Return chicken to the skillet. Pour the sauce over everything and toss to combine.',
        'Cook for 1-2 minutes until the sauce has thickened slightly.',
        'Serve immediately over cooked rice.',
    ],
    imageId: 'spicy-chicken-stir-fry',
    nutritionalInfo: { calories: '450 kcal', protein: '40g', carbs: '30g', fat: '18g' },
  },
  {
    id: '5',
    slug: 'mediterranean-quinoa-salad',
    title: 'Mediterranean Quinoa Salad',
    description: 'A light, refreshing, and protein-packed salad with classic Mediterranean flavors.',
    cuisine: 'Mediterranean',
    mealType: 'Lunch',
    dietaryRestrictions: ['Gluten-Free', 'Vegetarian'],
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    ingredients: [
        { name: 'Quinoa', quantity: '1 cup, uncooked' },
        { name: 'Cucumber', quantity: '1, diced' },
        { name: 'Cherry tomatoes', quantity: '1 cup, halved' },
        { name: 'Red onion', quantity: '1/4, finely chopped' },
        { name: 'Kalamata olives', quantity: '1/2 cup, pitted' },
        { name: 'Feta cheese', quantity: '1/2 cup, crumbled' },
        { name: 'Lemon juice', quantity: '1/4 cup' },
        { name: 'Olive oil', quantity: '3 tbsp' },
        { name: 'Fresh dill', quantity: '2 tbsp, chopped' },
    ],
    instructions: [
        'Cook quinoa according to package directions. Let cool completely.',
        'In a large bowl, combine the cooled quinoa, cucumber, tomatoes, red onion, olives, and feta cheese.',
        'In a small bowl, whisk together the lemon juice, olive oil, and dill. Season with salt and pepper.',
        'Pour the dressing over the salad and toss to combine.',
        'Let the salad sit for at least 15 minutes for the flavors to meld.',
        'Serve chilled or at room temperature.',
    ],
    imageId: 'mediterranean-quinoa-salad',
    nutritionalInfo: { calories: '400 kcal', protein: '12g', carbs: '45g', fat: '20g' },
  },
  {
    id: '6',
    slug: 'classic-beef-tacos',
    title: 'Classic Beef Tacos',
    description: 'A family-favorite for a reason! These simple and delicious beef tacos are perfect for a fun and easy dinner.',
    cuisine: 'Mexican',
    mealType: 'Dinner',
    dietaryRestrictions: [],
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    ingredients: [
        { name: 'Ground beef', quantity: '1 lb' },
        { name: 'Taco seasoning', quantity: '1 packet' },
        { name: 'Water', quantity: '1/2 cup' },
        { name: 'Hard taco shells', quantity: '8' },
        { name: 'Lettuce', quantity: 'shredded' },
        { name: 'Tomatoes', quantity: 'diced' },
        { name: 'Cheddar cheese', quantity: 'shredded' },
        { name: 'Sour cream', quantity: 'optional' },
    ],
    instructions: [
        'In a large skillet, cook ground beef over medium-high heat until no longer pink. Drain excess fat.',
        'Stir in taco seasoning and water. Bring to a simmer and cook for 5 minutes, or until sauce has thickened.',
        'While the meat is cooking, warm taco shells according to package directions.',
        'Assemble tacos by filling shells with beef mixture and desired toppings like lettuce, tomatoes, cheese, and sour cream.',
        'Serve immediately.',
    ],
    imageId: 'classic-beef-tacos',
    nutritionalInfo: { calories: '380 kcal', protein: '25g', carbs: '20g', fat: '22g' },
  }
];

export const getRecipes = (): Recipe[] => RECIPES;

export const getRecipeBySlug = (slug: string): Recipe | undefined => {
  return RECIPES.find((recipe) => recipe.slug === slug);
}

export const getCuisines = (): string[] => {
  return [...new Set(RECIPES.map(r => r.cuisine))];
};

export const getMealTypes = (): string[] => {
  return [...new Set(RECIPES.map(r => r.mealType))];
};
